import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Clapperboard, Play, Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function fetchGenere(): Promise<{ id: string; name: string }[]> {
  const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
    headers: {
      Authorization: `Bearer ${process.env.TMDB_TOKEN}`,
    },
  });
  const data = await res.json();
  return data.genres;
}
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const generes = await fetchGenere();
  const handleSearch = async function (form: FormData) {
    "use server";
    const query = form.get("query");
    redirect(`/search?query=${query}`);
  };

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="p-4 border-b flex flex-row justify-between items-center">
          <h1 className="text-3xl font-bold flex flex-row gap-2 items-center">
            <Clapperboard />
            Movie App
          </h1>
          <form action={handleSearch} className="flex gap-2">
            <Input placeholder="Search...." name="query" />
            <Button type="submit">
              <Search />
            </Button>
          </form>
        </header>
        <main className="flex flex-row">
          <nav className="w-50 p-4 boder-r flex flex-col shrink-0 gap-1">
            <Button variant="outline" asChild>
              <Link href={"/"} className="justify-start py-5">
                <Play />
                All Movie
              </Link>
            </Button>
            {generes.map((genre) => {
              return (
                <Button key={genre.id} variant="outline" asChild>
                  <Link
                    href={`/genre/${genre.name}/${genre.id}`}
                    className="justify-start py-5"
                  >
                    <Play />
                    {genre.name}
                  </Link>
                </Button>
              );
            })}
          </nav>
          <section className="p-4">{children}</section>
        </main>
      </body>
    </html>
  );
}
